#!/bin/bash
set -euo pipefail

ALEMBIC_FILE=/opt/deploy/configs/alembic.ini

python3 - <<'PY'
from pathlib import Path

env = {}
for line in Path("/opt/deploy/.env").read_text().splitlines():
    if "=" in line and not line.strip().startswith("#"):
        k, v = line.split("=", 1)
        env[k.strip()] = v.strip()

user = env.get("MYSQL_USER", "closet")
password = env.get("MYSQL_PASSWORD", "")
database = env.get("MYSQL_DATABASE", "closet_management")
url = f"mysql+pymysql://{user}:{password}@db:3306/{database}?charset=utf8mb4"

ini = f"""# Generated by migrate.sh — do not commit (see deploy/.gitignore)

[alembic]
script_location = database
prepend_sys_path = .
version_path_separator = os

sqlalchemy.url = {url}

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""

Path("/opt/deploy/configs").mkdir(parents=True, exist_ok=True)
Path("/opt/deploy/configs/alembic.ini").write_text(ini)
print("ALEMBIC_INI_OK")
PY

docker compose -f /opt/deploy/docker-compose.yml cp "$ALEMBIC_FILE" backend:/opt/deploy/backend/alembic.ini
docker compose -f /opt/deploy/docker-compose.yml exec -T backend sh -c "cd /opt/deploy/backend && python -m alembic upgrade head"
echo "MIGRATION_OK"
